services:
  db:
    image: postgres:15-alpine
    container_name: hayai_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hayai_db
      - POSTGRES_USER=hayai_user
      - POSTGRES_PASSWORD=hayai_secure_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: hayai_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: